[2023-07-04T11:03:49.096+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Email_dag1.send_email scheduled__2023-06-02T00:00:00+00:00 [queued]>
[2023-07-04T11:03:49.103+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Email_dag1.send_email scheduled__2023-06-02T00:00:00+00:00 [queued]>
[2023-07-04T11:03:49.103+0530] {taskinstance.py:1308} INFO - Starting attempt 14 of 15
[2023-07-04T11:03:49.133+0530] {taskinstance.py:1327} INFO - Executing <Task(EmailOperator): send_email> on 2023-06-02 00:00:00+00:00
[2023-07-04T11:03:49.136+0530] {standard_task_runner.py:57} INFO - Started process 21386 to run task
[2023-07-04T11:03:49.139+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Email_dag1', 'send_email', 'scheduled__2023-06-02T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_email_operator.py', '--cfg-path', '/tmp/tmpohmjrk15']
[2023-07-04T11:03:49.140+0530] {standard_task_runner.py:85} INFO - Job 146: Subtask send_email
[2023-07-04T11:03:49.194+0530] {task_command.py:410} INFO - Running <TaskInstance: Email_dag1.send_email scheduled__2023-06-02T00:00:00+00:00 [running]> on host neosoft-Latitude-E5270
[2023-07-04T11:03:49.271+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nikitaneti21@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Email_dag1' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2023-06-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-02T00:00:00+00:00'
[2023-07-04T11:03:49.283+0530] {logging_mixin.py:149} WARNING - /home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py:152 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-07-04T11:03:49.283+0530] {configuration.py:674} WARNING - section/key [smtp/smtp_user] not found in config
[2023-07-04T11:03:49.283+0530] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-04T11:03:49.284+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 78, in send_email
    return backend(
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2023-07-04T11:03:49.287+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=Email_dag1, task_id=send_email, execution_date=20230602T000000, start_date=20230704T053349, end_date=20230704T053349
[2023-07-04T11:03:49.323+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 146 for task send_email ([Errno 111] Connection refused; 21386)
[2023-07-04T11:03:49.351+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-04T11:03:49.390+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
