[2023-07-04T11:12:27.064+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Email_dag1.send_email scheduled__2023-06-02T00:00:00+00:00 [queued]>
[2023-07-04T11:12:27.071+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Email_dag1.send_email scheduled__2023-06-02T00:00:00+00:00 [queued]>
[2023-07-04T11:12:27.071+0530] {taskinstance.py:1308} INFO - Starting attempt 17 of 21
[2023-07-04T11:12:27.109+0530] {taskinstance.py:1327} INFO - Executing <Task(EmailOperator): send_email> on 2023-06-02 00:00:00+00:00
[2023-07-04T11:12:27.113+0530] {standard_task_runner.py:57} INFO - Started process 27944 to run task
[2023-07-04T11:12:27.119+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Email_dag1', 'send_email', 'scheduled__2023-06-02T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_email_operator.py', '--cfg-path', '/tmp/tmpolbhym2x']
[2023-07-04T11:12:27.120+0530] {standard_task_runner.py:85} INFO - Job 150: Subtask send_email
[2023-07-04T11:12:27.176+0530] {task_command.py:410} INFO - Running <TaskInstance: Email_dag1.send_email scheduled__2023-06-02T00:00:00+00:00 [running]> on host neosoft-Latitude-E5270
[2023-07-04T11:12:27.248+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nikitaneti21@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Email_dag1' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2023-06-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='17' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-02T00:00:00+00:00'
[2023-07-04T11:12:27.255+0530] {base.py:73} INFO - Using connection ID 'Email_default' for task execution.
[2023-07-04T11:12:27.255+0530] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-04T11:12:27.256+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 78, in send_email
    return backend(
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2023-07-04T11:12:27.260+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=Email_dag1, task_id=send_email, execution_date=20230602T000000, start_date=20230704T054227, end_date=20230704T054227
[2023-07-04T11:12:27.286+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 150 for task send_email ([Errno 111] Connection refused; 27944)
[2023-07-04T11:12:27.294+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-04T11:12:27.307+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
