[2023-06-29T12:07:51.553+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_v2.second_task scheduled__2023-06-28T00:00:00+00:00 [queued]>
[2023-06-29T12:07:51.559+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_v2.second_task scheduled__2023-06-28T00:00:00+00:00 [queued]>
[2023-06-29T12:07:51.559+0530] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-29T12:07:51.585+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): second_task> on 2023-06-28 00:00:00+00:00
[2023-06-29T12:07:51.588+0530] {standard_task_runner.py:57} INFO - Started process 71369 to run task
[2023-06-29T12:07:51.591+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_v2', 'second_task', 'scheduled__2023-06-28T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bash_operator.py', '--cfg-path', '/tmp/tmpt7p0fnka']
[2023-06-29T12:07:51.592+0530] {standard_task_runner.py:85} INFO - Job 70: Subtask second_task
[2023-06-29T12:07:51.647+0530] {task_command.py:410} INFO - Running <TaskInstance: Dag_v2.second_task scheduled__2023-06-28T00:00:00+00:00 [running]> on host neosoft-Latitude-E5270
[2023-06-29T12:07:51.722+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-28T00:00:00+00:00'
[2023-06-29T12:07:51.723+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-06-29T12:07:51.724+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo,i am task2 & will be running after task1!']
[2023-06-29T12:07:51.730+0530] {subprocess.py:86} INFO - Output:
[2023-06-29T12:07:51.736+0530] {subprocess.py:93} INFO - /usr/bin/bash: echo,i: command not found
[2023-06-29T12:07:51.737+0530] {subprocess.py:93} INFO - /usr/bin/bash: will: command not found
[2023-06-29T12:07:51.737+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-29T12:07:51.746+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-29T12:07:51.748+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=Dag_v2, task_id=second_task, execution_date=20230628T000000, start_date=20230629T063751, end_date=20230629T063751
[2023-06-29T12:07:51.773+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 70 for task second_task (Bash command failed. The command returned a non-zero exit code 127.; 71369)
[2023-06-29T12:07:51.803+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-29T12:07:51.836+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
