[2023-06-29T11:10:33.698+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_v2.first_task manual__2023-06-28T13:18:39.902218+00:00 [queued]>
[2023-06-29T11:10:33.710+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_v2.first_task manual__2023-06-28T13:18:39.902218+00:00 [queued]>
[2023-06-29T11:10:33.710+0530] {taskinstance.py:1308} INFO - Starting attempt 9 of 12
[2023-06-29T11:10:33.743+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-06-28 13:18:39.902218+00:00
[2023-06-29T11:10:33.747+0530] {standard_task_runner.py:57} INFO - Started process 24448 to run task
[2023-06-29T11:10:33.754+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_v2', 'first_task', 'manual__2023-06-28T13:18:39.902218+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bash_operator.py', '--cfg-path', '/tmp/tmpv8hraqt9']
[2023-06-29T11:10:33.756+0530] {standard_task_runner.py:85} INFO - Job 57: Subtask first_task
[2023-06-29T11:10:33.832+0530] {task_command.py:410} INFO - Running <TaskInstance: Dag_v2.first_task manual__2023-06-28T13:18:39.902218+00:00 [running]> on host neosoft-Latitude-E5270
[2023-06-29T11:10:33.920+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_v2' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-28T13:18:39.902218+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-28T13:18:39.902218+00:00'
[2023-06-29T11:10:33.923+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-06-29T11:10:33.923+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'this is the first task']
[2023-06-29T11:10:33.933+0530] {subprocess.py:86} INFO - Output:
[2023-06-29T11:10:33.939+0530] {subprocess.py:93} INFO - /usr/bin/bash: this: command not found
[2023-06-29T11:10:33.941+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-29T11:10:33.953+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-29T11:10:33.959+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=Dag_v2, task_id=first_task, execution_date=20230628T131839, start_date=20230629T054033, end_date=20230629T054033
[2023-06-29T11:10:33.993+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 57 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 24448)
[2023-06-29T11:10:34.010+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-29T11:10:34.041+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
