[2023-06-29T11:16:40.768+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_v2.first_task manual__2023-06-28T13:18:39.902218+00:00 [queued]>
[2023-06-29T11:16:40.774+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_v2.first_task manual__2023-06-28T13:18:39.902218+00:00 [queued]>
[2023-06-29T11:16:40.775+0530] {taskinstance.py:1308} INFO - Starting attempt 12 of 12
[2023-06-29T11:16:40.807+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-06-28 13:18:39.902218+00:00
[2023-06-29T11:16:40.814+0530] {standard_task_runner.py:57} INFO - Started process 30097 to run task
[2023-06-29T11:16:40.825+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_v2', 'first_task', 'manual__2023-06-28T13:18:39.902218+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bash_operator.py', '--cfg-path', '/tmp/tmpu3ps4fa7']
[2023-06-29T11:16:40.827+0530] {standard_task_runner.py:85} INFO - Job 62: Subtask first_task
[2023-06-29T11:16:40.922+0530] {task_command.py:410} INFO - Running <TaskInstance: Dag_v2.first_task manual__2023-06-28T13:18:39.902218+00:00 [running]> on host neosoft-Latitude-E5270
[2023-06-29T11:16:40.987+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_v2' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-28T13:18:39.902218+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-28T13:18:39.902218+00:00'
[2023-06-29T11:16:40.989+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-06-29T11:16:40.989+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'this is the first task']
[2023-06-29T11:16:40.996+0530] {subprocess.py:86} INFO - Output:
[2023-06-29T11:16:40.998+0530] {subprocess.py:93} INFO - /usr/bin/bash: this: command not found
[2023-06-29T11:16:40.998+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-29T11:16:41.007+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-29T11:16:41.009+0530] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=Dag_v2, task_id=first_task, execution_date=20230628T131839, start_date=20230629T054640, end_date=20230629T054641
[2023-06-29T11:16:41.036+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 62 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 30097)
[2023-06-29T11:16:41.076+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-29T11:16:41.104+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
