[2023-06-28T17:33:18.215+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG-2.second_task manual__2023-06-28T11:52:59.033036+00:00 [queued]>
[2023-06-28T17:33:18.223+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG-2.second_task manual__2023-06-28T11:52:59.033036+00:00 [queued]>
[2023-06-28T17:33:18.223+0530] {taskinstance.py:1308} INFO - Starting attempt 6 of 6
[2023-06-28T17:33:18.248+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): second_task> on 2023-06-28 11:52:59.033036+00:00
[2023-06-28T17:33:18.251+0530] {standard_task_runner.py:57} INFO - Started process 249510 to run task
[2023-06-28T17:33:18.255+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'DAG-2', 'second_task', 'manual__2023-06-28T11:52:59.033036+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bash_operator.py', '--cfg-path', '/tmp/tmpu6aila4i']
[2023-06-28T17:33:18.256+0530] {standard_task_runner.py:85} INFO - Job 35: Subtask second_task
[2023-06-28T17:33:18.350+0530] {task_command.py:410} INFO - Running <TaskInstance: DAG-2.second_task manual__2023-06-28T11:52:59.033036+00:00 [running]> on host neosoft-Latitude-E5270
[2023-06-28T17:33:18.417+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='DAG-2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-28T11:52:59.033036+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-28T11:52:59.033036+00:00'
[2023-06-28T17:33:18.419+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-06-28T17:33:18.419+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'this is the second task']
[2023-06-28T17:33:18.426+0530] {subprocess.py:86} INFO - Output:
[2023-06-28T17:33:18.427+0530] {subprocess.py:93} INFO - /usr/bin/bash: this: command not found
[2023-06-28T17:33:18.427+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-28T17:33:18.435+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-28T17:33:18.438+0530] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=DAG-2, task_id=second_task, execution_date=20230628T115259, start_date=20230628T120318, end_date=20230628T120318
[2023-06-28T17:33:18.472+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task second_task (Bash command failed. The command returned a non-zero exit code 127.; 249510)
[2023-06-28T17:33:18.507+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-28T17:33:18.539+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
